### ISSUE TITLE
[Bug] Crop Image by ratio not resizing image to width and height

### ISSUE THREAD

**Issue by SkandarClubforce** [icapps/flutter-custom-image-crop#42]
After perform image crop by ratio, the width and height should correspond to the give crop ration, but for some reason the plugin still treat the final image width and height as square.

Needs fixing.

**Comment by MichalNemec** [comment]
just stumbled upon this issue also.
Ratio 2 : 1 -> image is square afterwards with black background.

**Comment by MichalNemec** [comment]
based on closed issues like #39 i understand, but images can be rectangle also.

**Comment by MichalNemec** [comment]
@ikbendewilliam Could we have some guidance how to solve this, since ratio is in the code?

If there is nothing to be done, Do you have any idea, how can we "cut" the images so that its properly rendered in circleavatar? We want Rectangle, so it can be used on tablets (square looks ugly) on backgrounds as header, we also need circleavatar and we can see the black bars. is there a way to somehow hide it and make the image contain properly?

<img width="57" alt="image" src="https://github.com/icapps/flutter-custom-image-crop/assets/5663019/7ff07ab1-5fa4-4c15-8760-4e40d9d147b8">

`BoxFit.cover`
<img width="605" alt="image" src="https://github.com/icapps/flutter-custom-image-crop/assets/5663019/51fe99ed-e3c5-4d48-b55e-b575bd9bc43c">

'BoxFit.contain`
<img width="608" alt="image" src="https://github.com/icapps/flutter-custom-image-crop/assets/5663019/45743b68-8282-4a76-9ded-99e39e867282">

**Comment by ikbendewilliam** [comment]
Hi, I missed the issue, apologies. I'll look at it next week as we're close to a hard deadline. 
This is indeed an oversight when the crop ratio has been added, but doesn't sound to difficult to fix. The canvas we create is indeed a square atm and should instead adhere to the ratio. Feel free to create a PR if you're able to fix it before I have the time 😁

**Comment by ikbendewilliam** [comment]
Fixed in 0.0.12
